version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    entrypoint: ["./app-entrypoint.sh"]
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app  
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"  
    depends_on: 
      - db  
  nginx:
    build: 
      context: nginx
    container_name: nginx
    entrypoint: ["./entrypoint.sh"]
    restart: always
    tty: true
    ports:  
      - "8080:80"
    networks: 
      - node-network 
    depends_on: 
      - app
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/setup:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passw0rd
    networks: 
      - node-network  
networks: 
  node-network:
    driver: bridge


    
    
