version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    entrypoint: ["./app-entrypoint.sh"]  
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app  
    tty: true
    ports: 
      - "8085:3000"  
    depends_on: 
      - db  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/setup:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passw0rd
    networks: 
      - node-network  
networks: 
  node-network:
    driver: bridge


    
    
